#!/bin/sh /etc/rc.common
START=99

USE_PROCD=1
BIN="/usr/bin/python /root/smart-plant/smartPlant.py --quiet --losant /root/smart-plant/losant.json --pump > /dev/null 2>&1 &"


start_service() {
    procd_open_instance
    procd_set_param command $BIN
    procd_set_param respawn
    procd_close_instance
}
